### ISSUE TITLE
500 Error on Location Details Page

### ISSUE THREAD

**Issue by frizman21** [houseofsticks/Watermark#19]
Getting a 500 error on all the location details page. Dallas and Forth Worth seem to work - others do not.
http://dev-porch-rails.herokuapp.com/locations/spring

![image](https://user-images.githubusercontent.com/11731079/29680045-fe85dea8-88c8-11e7-8910-a64b3737a9d8.png)

**Comment by makeshcwsl** [comment]
Fixed the issue.
