### ISSUE TITLE
Emails from website failed to send

### ISSUE THREAD

**Issue by frizman21** [houseofsticks/Watermark#27]
![image](https://user-images.githubusercontent.com/11731079/30350613-1d1a737e-97dd-11e7-9df2-7d24cdf6e9b6.png)

**Comment by frizman21** [comment]
And Contact Us Page
![image](https://user-images.githubusercontent.com/11731079/30350657-4b09a6a6-97dd-11e7-913b-e25b8e883d75.png)

**Comment by jpowell** [comment]
Sendgrid Creds

**Comment by frizman21** [comment]
Our sendgrid creds added to production and staging.
