### ISSUE TITLE
Watermark Live Player

### ISSUE THREAD

**Issue by makeshcwsl** [houseofsticks/Watermark#4]
Need documentation & access to Watermark api.

**Comment by jpowell** [comment]
https://media.watermark.org/api/help

I shared this link last week. Is this what you're referring to?

**Comment by jpowell** [comment]
We will get you the live stream info

**Comment by frizman21** [comment]
Here's the smallest, best example
https://player.streammonkey.com/iframe/2441

**Comment by jpowell** [comment]
closing in favor of #8
