### ISSUE TITLE
AddThis for social sharing

### ISSUE THREAD

**Issue by jpowell** [houseofsticks/Watermark#7]
https://www.addthis.com/academy/how-to-install-addthis-code/

```html
<!-- in head script area -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5981d71557621d90"></script>


<!-- inline where we want the links -->
<div class="addthis_inline_share_toolbox"></div>
```

**Comment by jpowell** [comment]
Let me know if you have any issues with that... the configuration is on our end. You can take the markup they give you and modify what they render on the client side.

**Comment by jpowell** [comment]
Looks to be done?

/cc @frizman21

**Comment by frizman21** [comment]
agreed
